scrape_configs:
 - job_name: 'prometheus'
   static_configs:
   - targets: ['localhost:9090'] 

 - job_name: bot_metrics
   scrape_interval: 30s
   scrape_timeout:  1m
   metrics_path: "/metrics" 
   static_configs: 
   - targets: ['localhost:9100']

 - job_name: server_metrics
   scrape_interval: 20s
   scrape_timeout:  10s
   metrics_path: "/metrics" 
   static_configs: 
   - targets: ['host.docker.internal:9100']

 - job_name: user_exporter
   scrape_interval: 1m
   scrape_timeout:  1m
   metrics_path: "/metrics" 
   static_configs: 
   - targets: ['localhost:9877']