app:
  name: STUDOT
  version: 1.0

  timezone:
    name: MSC
    offset: 3

  metrics:
    filepath: "data/metrics/metrics"
    fields:
      - Place
      - Course
      - Group
      - UserId
      - Social
    timing: yes
    storage: CSV
    available-storage-types:
      - CSV
      - Mongo
      - Text
    export-port: 9877

  site-scanner:
    time-interval: "10 m" # h, m, s

  files:
    path: "files/"
    max-count: 8